* 简介
* 使用实例
** 连接复用
   很多时候，有一些使用ssh的程序，例如git
   
   Host *
	     ControlMaster auto
	     ControlPath ~/.ssh/socket-%r@%h:%p
	     ControlPersist yes
   1.Host 指令
     表明下面的配置项在连接到任何远程主机时都有效，也可以通过类似 *.example.com 的其他模式来匹配指定的远程主机。
   2.ControlMaster 选项
     表明是否在 ControlPath 指定的路径上创建一个控制套接字以便复用底层的 SSH 连接。
     如果值为 yes，当前会话将在指定路径上创建一个域套接字作为控制套接字，并且监听新连接；
     如果值为 no，当前会话将寻找是否有对应的正在监听的控制套接字，如果找到则通过此控制套接字复用之前已建立的 SSH 连接，如果没找到则进行常规的会话创建（新建一个独立的 SSH 连接，并且不创建控制套接字）。
     如果值为 auto，表示如果有控制套接字则复用连接，如果没有则自己完成与远程主机的连接后创建控制套接字。
   3.ControlPath 选项
     指定控制套接字的路径，%r 表示登录名，%h 表示远程主机名， %p 表示远程主机端口。控制套接字的路径应该至少包含这三项，以唯一标识一个 SSH 连接。
   4.ControlPersist 选项
     表明在创建控制套接字的会话（下面称为主会话）结束后，SSH 连接是否在后台继续存活。
     如果值为 no，在有会话复用连接的情况下，退出主会话时进程将会挂起，此时用 Ctrl+C 杀掉进程，此连接上的其他会话将会退出，SSH 和控制套接字都将关闭。
     如果值为 yes，则主会话关闭后连接会在后台永久存活。另外，这个选项的值也可以是一个时间（比如600s或1h），表示主会话关闭后连接在后台可存活的最长时间

     开启了 4. 里面描述的 SSH 连接继续存活的选项后，手动关闭 socket：
     ssh -0 exit ~/.ssh/socket-xxxx@xxxx:xx    #?????????????????好像不对
* 参数详解
* 配置文件详解
